@echo off
echo Configurando novo repositorio...
git remote set-url origin https://github.com/Wescleys/ITIL4Quiz.git
echo Copiando arquivos do site...
xcopy /E /Y /I dist\* .
echo Preparando commit...
git add .
git commit -m "Deploy manual: Site completo na main"
echo Subindo para o GitHub (Main)...
git push -f origin main
echo Tudo pronto!
